name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

env:
  ACTIONS_STEP_DEBUG: true
jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Upgrade npm
        run: npm install -g npm@11.4.2

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - run: |
          echo "{}" > otel-metrics.json

      - name: Test Local Action
        uses: ./
        with:
          endpoint: ${{secrets.OTEL_TESTING_ENDPOINT}}
          headers: |
            x-custom-header-1: "test1"
            x-custom-header-2: "test2"
          metricNamespace: cve
          repositoryName: ${{env.GITHUB_REPOSITORY}}
          serviceNameAttr: ci-action-trivy
          serviceVersionAttr: 1.0.0
          trivyOutputFile: otel-metrics.json
          trivyFormat: sarif
